apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    name: backend
  name: backend-svc
  namespace: fireforcedefense-27426248
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: backend
    name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
    name: backend
  name: backend
  namespace: fireforcedefense-27426248
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      name: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
        name: backend
    spec:
      containers:
      - name: backend
        image: 285302907374.dkr.ecr.eu-central-1.amazonaws.com/backend
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000