apiVersion: v1
kind: ServiceAccount
metadata:
  name: fireforcedefense-27426248-service-account
  namespace: fireforcedefense-27426248
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fireforcedefense-27426248-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: fireforcedefense-27426248-service-account
    namespace: fireforcedefense-27426248