apiVersion: v1
kind: ServiceAccount
metadata:
  name: ffd-prod-service-account
  namespace: ffd-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ffd-prod-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ffd-prod-service-account
    namespace: ffd-prod